<?php

use Force10\Laravel\ManifestWriter;
use Force10\Laravel\ManifestEntry;

beforeEach(function () {
    $this->writer = new ManifestWriter();
    $this->outputPath = tempnam(sys_get_temp_dir(), 'force10_manifest_') . '.ts';
});

afterEach(function () {
    if (file_exists($this->outputPath)) {
        unlink($this->outputPath);
    }
});

it('generates valid TypeScript manifest file', function () {
    $entries = [
        new ManifestEntry('/about', 'About'),
    ];

    $this->writer->writeTypeScript($entries, $this->outputPath);

    $content = file_get_contents($this->outputPath);
    expect($content)->toContain('export default');
    expect($content)->toContain('routes');
});

it('includes all route entries', function () {
    $entries = [
        new ManifestEntry('/about', 'About'),
        new ManifestEntry('/users', 'Users/Index', ['auth']),
        new ManifestEntry('/users/:id', 'Users/Show', ['auth'], [['name' => 'id', 'required' => true]]),
    ];

    $this->writer->writeTypeScript($entries, $this->outputPath);

    $content = file_get_contents($this->outputPath);
    expect($content)->toContain('About');
    expect($content)->toContain('Users/Index');
    expect($content)->toContain('Users/Show');
});

it('generates correct route patterns', function () {
    $entries = [
        new ManifestEntry('/users/:id', 'Users/Show'),
        new ManifestEntry('/teams/:teamId/members/:memberId', 'Teams/Members/Show'),
    ];

    $this->writer->writeTypeScript($entries, $this->outputPath);

    $content = file_get_contents($this->outputPath);
    expect($content)->toContain('/users/:id');
    expect($content)->toContain('/teams/:teamId/members/:memberId');
});

it('includes middleware arrays', function () {
    $entries = [
        new ManifestEntry('/dashboard', 'Dashboard', ['auth', 'verified']),
    ];

    $this->writer->writeTypeScript($entries, $this->outputPath);

    $content = file_get_contents($this->outputPath);
    expect($content)->toContain('auth');
    expect($content)->toContain('verified');
});

it('includes metadata comments', function () {
    $entries = [
        new ManifestEntry('/about', 'About'),
    ];

    $this->writer->writeTypeScript($entries, $this->outputPath);

    $content = file_get_contents($this->outputPath);
    expect($content)->toContain('Generated by Force10');
});
