<?php

namespace Force10\Laravel;

class ManifestWriter
{
    /**
     * Write the manifest entries as a TypeScript file.
     *
     * @param ManifestEntry[] $entries
     */
    public function writeTypeScript(array $entries, string $outputPath): void
    {
        $routes = [];

        foreach ($entries as $entry) {
            $routes[] = $this->formatRouteEntry($entry);
        }

        $routesJson = implode(",\n", $routes);

        $content = <<<TS
// Generated by Force10
// Do not edit this file manually.

export default {
  routes: [
{$routesJson}
  ],
};
TS;

        $dir = dirname($outputPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        file_put_contents($outputPath, $content);
    }

    /**
     * Format a single ManifestEntry as a TypeScript object literal.
     */
    protected function formatRouteEntry(ManifestEntry $entry): string
    {
        $pattern = $this->escapeString($entry->pattern);
        $component = $this->escapeString($entry->component);
        $middleware = $this->formatStringArray($entry->middleware);
        $parameters = $this->formatParameters($entry->parameters);

        return "    {\n" .
            "      pattern: '{$pattern}',\n" .
            "      component: '{$component}',\n" .
            "      middleware: {$middleware},\n" .
            "      parameters: {$parameters},\n" .
            "    }";
    }

    /**
     * Escape a string for use in a TypeScript string literal.
     */
    protected function escapeString(string $value): string
    {
        return str_replace(["'", "\\"], ["\\'", "\\\\"], $value);
    }

    /**
     * Format an array of strings as a TypeScript array literal.
     */
    protected function formatStringArray(array $items): string
    {
        if (empty($items)) {
            return '[]';
        }

        $escaped = array_map(fn (string $item) => "'" . $this->escapeString($item) . "'", $items);

        return '[' . implode(', ', $escaped) . ']';
    }

    /**
     * Format parameter definitions as a TypeScript array literal.
     */
    protected function formatParameters(array $parameters): string
    {
        if (empty($parameters)) {
            return '[]';
        }

        $items = array_map(function (array $param) {
            $name = $this->escapeString($param['name']);
            $required = $param['required'] ? 'true' : 'false';

            return "{ name: '{$name}', required: {$required} }";
        }, $parameters);

        return '[' . implode(', ', $items) . ']';
    }
}
